spring:
  profiles.active: develop
---
spring:
  profiles: develop
  datasource:
    driver-class-name: org.sqlite.JDBC
    url: jdbc:sqlite:test.db

---
spring:
  profiles: release
  dataSource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&useSSL=true&characterEncoding=utf-8
    username: root
    password: root

---
spring:
  mustache:
    charset: utf-8
    cache: false

---
logging:
  level:
    cn:
      ttzero:
        zly:
          mapper: debug